version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./.mongodb/database:/data/db
    ports:
      - 27017:27017
